#!/usr/bin/env node
// Extract the Cadence transaction string from lib/cadence/purchase-moment.ts
// and write it to tests/cadence/fixtures/purchase-moment.cdc with
// address-form imports rewritten to string-form so `flow cadence lint`
// can resolve them via tests/cadence/flow.test.json.
//
// The fixture is gitignored — it is regenerated on every run of
// `npm run test:cadence`. Editing the fixture by hand has no effect; edit
// lib/cadence/purchase-moment.ts (when bug fixes land) and re-run.
//
// Run directly: node scripts/extract-cadence.mjs

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..");
const sourcePath = join(repoRoot, "lib", "cadence", "purchase-moment.ts");
const outDir = join(repoRoot, "tests", "cadence", "fixtures");
const outPath = join(outDir, "purchase-moment.cdc");

const tsSource = readFileSync(sourcePath, "utf8");

const match = tsSource.match(
  /export\s+const\s+PURCHASE_MOMENT_CADENCE\s*=\s*`([\s\S]*?)`/
);
if (!match) {
  console.error(
    "[extract-cadence] could not locate PURCHASE_MOMENT_CADENCE template literal in",
    sourcePath
  );
  process.exit(1);
}

const cadenceRaw = match[1];

const cadenceTransformed = cadenceRaw.replace(
  /import[ \t]+([A-Za-z_][A-Za-z0-9_]*)[ \t]+from[ \t]+0x[0-9a-fA-F]+/g,
  'import "$1"'
);

const banner = [
  "// AUTO-GENERATED by scripts/extract-cadence.mjs — DO NOT EDIT BY HAND.",
  "// Source: lib/cadence/purchase-moment.ts (PURCHASE_MOMENT_CADENCE).",
  "// Address-form imports are rewritten to string-form for `flow cadence lint`.",
  "// To regenerate: npm run test:cadence",
  "",
].join("\n");

mkdirSync(outDir, { recursive: true });
writeFileSync(outPath, banner + cadenceTransformed.trimStart(), "utf8");

console.log("[extract-cadence] wrote", outPath);
