// lib/chains/solana/candy-checklist.ts
//
// Candy Digital's PUBLISHED checklist for 2026 MLB Base Series ICONs — the player
// column of docs/reference/candy-base-series-checklist-2026-07.csv (Candy's June
// 2026 checklist, recorded 2026-07). __tests__/candy-published-checklist.test.ts
// pins this list to that file, so the two cannot drift apart.
//
// WHY IT EXISTS (2026-09-25): RPC's Candy catalog is built from MINTED assets, so
// it holds 100 players while the published checklist names 103. Measured that
// day, Edwin Díaz, Austin Riley and Spencer Strider had no edition, sale or
// holding anywhere in RPC's data. The Set Tracker counts completion over the
// players RPC has seen; without this list it would call a 100-player wallet
// "complete" with no way for the reader to know the checklist is longer.
// The route computes the not-yet-seen names LIVE, so the note disappears on its
// own the day a card for one of them is minted and indexed.
//
// ⚠ Use this file for the PLAYER list only. The CSV's Rainbow column says /25 for
// Trout, Murakami, Witt Jr. and Caminero; the chain says /15 for all five Rainbow
// players (measured 2026-09-25: 75 held per player = 5 colours x 15, max serial
// 15 held and sold). The DB's circulation_count (15) is right; the CSV is not.

export const CANDY_PUBLISHED_CHECKLIST_PLAYERS: readonly string[] = [
  "Corbin Carroll",
  "Mickey Moniak",
  "Mookie Betts",
  "Edwin Díaz",
  "Freddie Freeman",
  "Shohei Ohtani",
  "Will Smith",
  "Kyle Tucker",
  "Andy Pages",
  "Yoshinobu Yamamoto",
  "Manny Machado",
  "Jackson Merrill",
  "Mason Miller",
  "Fernando Tatis Jr.",
  "Rafael Devers",
  "Logan Webb",
  "Jung Hoo Lee",
  "Bryce Eldridge",
  "Alex Bregman",
  "Pete Crow-Armstrong",
  "Nico Hoerner",
  "Seiya Suzuki",
  "Elly De La Cruz",
  "Chase Burns",
  "Hunter Greene",
  "Eugenio Suárez",
  "Oneil Cruz",
  "Paul Skenes",
  "Jackson Chourio",
  "William Contreras",
  "Jacob Misiorowski",
  "Brice Turang",
  "Christian Yelich",
  "Jordan Walker",
  "Ronald Acuña Jr.",
  "Ozzie Albies",
  "Drake Baldwin",
  "Matt Olson",
  "Austin Riley",
  "Chris Sale",
  "Spencer Strider",
  "Sandy Alcantara",
  "Otto Lopez",
  "Kyle Stowers",
  "Bo Bichette",
  "Francisco Lindor",
  "Juan Soto",
  "Bryce Harper",
  "Cristopher Sánchez",
  "Kyle Schwarber",
  "Zack Wheeler",
  "CJ Abrams",
  "James Wood",
  "Zach Neto",
  "José Soriano",
  "Mike Trout",
  "Nick Kurtz",
  "Shea Langeliers",
  "Brent Rooker",
  "Jacob Wilson",
  "Logan Gilbert",
  "Cal Raleigh",
  "Bryan Woo",
  "Jacob deGrom",
  "Wyatt Langford",
  "Corey Seager",
  "Jose Altuve",
  "Yordan Alvarez",
  "Hunter Brown",
  "Colson Montgomery",
  "Munetaka Murakami",
  "Chase DeLauter",
  "Steven Kwan",
  "José Ramírez",
  "Riley Greene",
  "Kevin McGonigle",
  "Tarik Skubal",
  "Framber Valdez",
  "Jac Caglianone",
  "Vinnie Pasquantino",
  "Salvador Perez",
  "Bobby Witt Jr.",
  "Byron Buxton",
  "Joe Ryan",
  "Pete Alonso",
  "Gunnar Henderson",
  "Adley Rutschman",
  "Roman Anthony",
  "Garrett Crochet",
  "Jarren Duran",
  "Ranger Suárez",
  "Cody Bellinger",
  "Jazz Chisholm Jr.",
  "Gerrit Cole",
  "Jasson Domínguez",
  "Max Fried",
  "Aaron Judge",
  "Ben Rice",
  "Junior Caminero",
  "Yandy Díaz",
  "Vladimir Guerrero Jr.",
  "Kazuma Okamoto",
  "George Springer",
]
