-- APPLIED LIVE 2026-08-28 23:08:05Z from Cowork (device-VM session). COMMIT ONLY — DO NOT RE-APPLY.
-- Version recorded by apply_migration: 20260828230805
-- Body below recovered VERBATIM from supabase_migrations.schema_migrations (pulled from prod, not retyped).
--
-- POST-FLIGHT, verified from OUTSIDE the migration 2026-08-28 23:09Z:
--   rows carrying 'HOUR PARITY IS REFUTED' = 1 · rows still carrying the old paragraph = 0
--   note_len 2370 -> 3236 · backup table still holds 1 row at the original 115 chars
--   stamp written = '2026-08-28 23:08Z', which matches the migration version exactly
--   check_secdef_anon_execute_violations() = []
--
-- ⓘ The stamp is generated by to_char(now()) INSIDE the migration rather than typed in. That is the
--   deliberate fix for the defect 20260828225210 shipped (a literal "22:5xZ" placeholder that then
--   needed two fixup migrations); a generated stamp cannot disagree with the register.

-- 2026-08-28 — resolve the hour-parity falsifier that 20260828225210 registered, from history,
-- the same day, instead of waiting 24 h. The note itself says "if it breaks, drop the idea"; it broke.
--
-- Guarded: anchors on the pipeline KEY and on the paragraph's opening phrase, idempotent via the
-- REFUTED marker, and RAISEs unless it matches exactly one row.
--
-- REVERT (restores the parity paragraph verbatim; name the relation exactly, NEVER wildcard
--         audit_20260828_*):
--   UPDATE public.pipeline_cadence_watchlist
--      SET notes = regexp_replace(notes, 'ⓘ [0-9-]{10} [0-9:]{5}Z — HOUR PARITY IS REFUTED[^\n]*\nⓘ[^\n]*\nⓘ[^\n]*\nⓘ[^\n]*\nⓘ[^\n]*',
--        'ⓘ Outcome alternated perfectly by hour parity 8/8 on 2026-08-28 (15 ok, 16 KILL, 17 ok, 18 KILL, 19 ok, 20 KILL, 21 ok, 22 KILL). ⛔ Do NOT conclude "even hours die" — the nine-day terminal-row counts (8-18 of 24) are arithmetically incompatible with a strict even-hour rule, which forces exactly 12/24. FALSIFIER: if the alternation still holds after a further 24 h the cause is a deterministic even-hour contender findable in cron.job; if it breaks, drop the idea.')
--    WHERE pipeline = 'refresh-pack-grail-metrics-mv';

DO $$
DECLARE n int;
DECLARE stamp text := to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI');
BEGIN
  UPDATE public.pipeline_cadence_watchlist
     SET notes = regexp_replace(
           notes,
           'ⓘ Outcome alternated[^\n]*',
           'ⓘ ' || stamp || 'Z — HOUR PARITY IS REFUTED. Do NOT hunt an even-hour contender in '
        || 'cron.job; the falsifier registered by 20260828225210 was resolved the same day, from '
        || 'history, without waiting 24 h. The 8/8 alternation was an 8-hour window (15-22Z on '
        || '08-28), not a law: on 2026-08-27 the EVEN hours 04, 06, 08 and 10 ALL wrote terminal '
        || 'rows — unambiguous positive evidence, since a terminal row can only exist if the tick '
        || 'ran to completion — and on 08-26 the ODD hours 09, 13 and 15 all missed.' || E'\n'
        || 'ⓘ ⛔ THE ONLY HONEST WINDOW IS ~72 h. pipeline_runs retains ~73 h, so a per-hour query '
        || 'over 9-10 days reads 70-100% missing at EVERY hour; that is the retention edge, not the '
        || 'pipeline. Measured 2026-08-25 23:23Z -> 2026-08-28 21:23Z, 71 ticks: 22 missing = 31%.' || E'\n'
        || 'ⓘ ⭐ WHAT REPEATS IS A PER-HOUR SET, NOT PARITY: hours 12, 13, 15, 16, 18 and 22 missed '
        || 'on all three days; every other hour missed on 0 or 1 of 3.' || E'\n'
        || 'ⓘ ⭐ AND pg_cron CONTENTION CANNOT BE THE WHOLE MECHANISM: summed pg_cron busy-seconds '
        || 'inside the tick 60 s window at 22:23Z is 5 on all three days (nothing else running), yet '
        || '22Z never survives.' || E'\n'
        || 'ⓘ FALSIFIER: re-run the 72 h per-hour table. If 12/13/15/16/18/22 is still the failing '
        || 'set, the cause is fixed-in-the-day and worth chasing at those hours; if the set moves, it '
        || 'is contention drift and only the IO-band story survives.')
   WHERE pipeline = 'refresh-pack-grail-metrics-mv'
     AND notes ~ 'ⓘ Outcome alternated perfectly by hour parity'
     AND notes NOT LIKE '%HOUR PARITY IS REFUTED%';

  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN
    RAISE EXCEPTION 'parity refutation matched % rows, expected exactly 1 (already applied, or the paragraph moved)', n;
  END IF;
END $$;